### ISSUE TITLE
Issue with Get-CsGroupId and hosts group names with spaces

### ISSUE THREAD

**Issue by dcoobs** [bk-cs/PSFalcon#21] opened 2020-06-18 14:42 UTC
Admittedly I haven't tested with a direct curl command to see if its your module or CrowdStrike's API itself, but I'm seeing issues with finding host groups by name when they have spaces in the group name. The query returns with an empty resources array. If I try with a group without spaces in the name, it works fine.

**Comment by bk-cs** [comment] 2020-06-19 20:32
Hi dcoobs,

Are you enclosing the group name in quotes? Could you provide an example of a failure and a success result?

Thanks!

**Comment by bk-cs** [comment] 2020-06-22 20:41
Hi dcoobs,

I was able to reproduce this issue. It looks like it's due to [System.Web.HttpUtility]::UrlEncode replacing spaces with "+" instead of "%20". There's another tool called UrlPathEncode that uses "%20", but for some reason Invoke-WebRequest (the core function in PSFalcon) seems to ignore it.

I've done some experimenting and have been unable to find a way to force Invoke-WebRequest to use "%20" for spaces, as it always ends up either converting them back into a space or a "+".

Unless someone finds a different way to handle this issue, I think I'd have to completely redesign how the requests to the API are being made in order to fix this problem.

**Comment by bk-cs** [comment] 2020-07-22 18:23
I found a way to fix this in PSFalcon v2. Once it's available for testing, I'll close this issue.

**Comment by bk-cs** [comment] 2021-01-16 01:20
I've started the release of PSFalcon v2. A few more steps remain before it's available on the PowerShell gallery, but it's close enough to close this issue.

https://github.com/crowdstrike/psfalcon

**Closed by bk-cs** 2021-01-16 01:20 UTC
Labels: bug
